query {
	  dealers {
          data {
            attributes {
              CompanyName
              CompanyDesc
              Coordinates
              StartTimeWork
              EndTimeWork
              VIP
              UID
            }
            id
          }
        }

}